# Generated by Django 2.1.2 on 2018-11-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181106_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='shelves',
            new_name='store_data',
        ),
    ]
