# Generated by Django 2.1.2 on 2018-11-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181106_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='store_data',
            new_name='products',
        ),
    ]
