# Generated by Django 2.1.3 on 2018-11-13 07:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181106_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='checkouts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[[0, 0]], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='entrances',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[[0, 0]], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='product_side',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First side (clock-wise)'), (2, 'Second side (clock-wise)'), (3, 'Third side (clock-wise)'), (4, 'Fourth side (clock-wise)')], default=1),
            preserve_default=False,
        ),
    ]
