const actionTypes = {
  SET_ACCOUNT: 'SET_ACCOUNT',
  INIT_NEARBY_STORES_FETCH: 'INIT_NEARBY_STORES_FETCH',
  SET_STORES: 'SET_STORES',
  INIT_STORES_FETCH_BY_NAME: 'INIT_STORES_FETCH_BY_NAME',
};

export {
  actionTypes,
};